[package]
name = "feedgarbologist"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4", features = ["derive"] }
feedbin_api = "0.2"
lazy_static = "1.4"
reqwest = "0.11"
tokio = { version = "1.27", features = ["full"] }
url = "2.3"
